import random
list_result = ['outlook is good','ask again later','yes','no','most likely no','most likely yes','maybe','outlook is not good']
q1 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q2 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q3 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q4 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q5 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q6 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q7 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
q8 = input("Please ask me a question:")
print(list_result[random.randint(0,len(list_result)-1)])
